/********************************************************************************
** Form generated from reading UI file 'fuseSettings.ui'
**
** Created by: Qt User Interface Compiler version 5.14.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FUSESETTINGS_H
#define UI_FUSESETTINGS_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>
#include "widgets/fuseSettings/avrFuseSettings.h"
#include "widgets/fuseSettings/picFuseSettings.h"

QT_BEGIN_NAMESPACE

class Ui_FuseSettings
{
public:
    QGridLayout *gridLayout;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QGroupBox *groupBox_4;
    QTextEdit *txtE_low_6;
    QLabel *label_5;
    QGroupBox *groupBox_5;
    QCheckBox *CHb_pic12_wdt;
    QCheckBox *CHb_pic12_pwrte;
    QCheckBox *CHb_pic12_boden;
    QCheckBox *CHb_pic12_wdt_2;
    QCheckBox *CHb_pic12_cpd;
    QCheckBox *CHb_pic12_CP;
    QLabel *label_6;
    QLabel *label_7;
    QGroupBox *groupBox_6;
    QRadioButton *Rd_pi12_03;
    QRadioButton *Rd_pi16_pof_2;
    QRadioButton *Rd_pi16_pof_3;
    QRadioButton *Rd_pi16_00;
    QGroupBox *groupBox_7;
    QRadioButton *Rd_pi12_lp;
    QRadioButton *Rd_pi12_xt;
    QRadioButton *Rd_pi12_hs;
    QRadioButton *Rd_pi12_ec_io;
    QRadioButton *Rd_pi12_osc_io;
    QRadioButton *Rd_pi12_osc_clkout;
    QRadioButton *Rd_pi12_rc_io;
    QRadioButton *Rd_pi12_rc_5;
    QWidget *page_3;
    QGroupBox *groupBox_8;
    QCheckBox *CHb_pic16_wdt_3;
    QCheckBox *CHb_pic16_pwrte_2;
    QCheckBox *CHb_pic16_boden_2;
    QCheckBox *CHb_pic16_wdt_4;
    QCheckBox *CHb_pic16_cpd_2;
    QCheckBox *CHb_pic16_CP_2;
    QLabel *label_8;
    QLabel *label_9;
    QGroupBox *groupBox_9;
    QRadioButton *Rd_pi16_pof_5;
    QRadioButton *Rd_pi16_pof_6;
    QRadioButton *Rd_pi16_pof_7;
    QRadioButton *Rd_pi16_pof_8;
    QGroupBox *groupBox_10;
    QRadioButton *Rd_pi16_lp_2;
    QRadioButton *Rd_pi16_xt_2;
    QRadioButton *Rd_pi16_hs_2;
    QRadioButton *Rd_pi16_rc_2;
    QCheckBox *CHb_pic16_debug_2;
    QGroupBox *groupBox_11;
    QTextEdit *txtE_low_7;
    QLabel *label_10;
    QWidget *page_7;
    QGroupBox *groupBox_25;
    QGroupBox *groupBox_28;
    QCheckBox *CHb_pic12_BOR0_5;
    QCheckBox *CHb_pic12_BOR1_5;
    QCheckBox *CHb_pic12_BOR2_5;
    QCheckBox *CHb_pic12_POR2_4;
    QCheckBox *CHb_pic12_POR0_5;
    QCheckBox *CHb_pic12_POR1_5;
    QCheckBox *CHb_pic12_fcalo_5;
    QCheckBox *CHb_pic12_fcalo1_5;
    QCheckBox *CHb_pic12_fcalo2_5;
    QCheckBox *CHb_pic12_fcalo3_5;
    QCheckBox *CHb_pic12_fcalo6_5;
    QCheckBox *CHb_pic12_fcalo5_5;
    QCheckBox *CHb_pic12_fcalo4_5;
    QLabel *label_29;
    QLabel *label_pic12_2019;
    QCheckBox *CHb_pic12_update_cal_5;
    QGroupBox *groupBox_29;
    QRadioButton *Rd_pi12_lp_6;
    QRadioButton *Rd_pi12_xt_6;
    QRadioButton *Rd_pi12_hs_6;
    QRadioButton *Rd_pi12_ec_io_6;
    QRadioButton *Rd_pi12_osc_io_6;
    QRadioButton *Rd_pi12_osc_clkout_6;
    QRadioButton *Rd_pi12_rc_io_6;
    QRadioButton *Rd_pi12_rc_10;
    QCheckBox *CHb_pic12_BODEN1_5;
    QCheckBox *CHb_pic12_wdt_7;
    QCheckBox *CHb_pic12_CP_6;
    QCheckBox *CHb_pic12_BODEN0_5;
    QCheckBox *CHb_pic12_pwrte_6;
    QCheckBox *CHb_pic12_cpd_6;
    QCheckBox *CHb_pic12_boden_6;
    QLabel *label_31;
    QLabel *label_pic12_2021;
    QCheckBox *CHb_pic12_IESO_5;
    QCheckBox *CHb_pic12_FCMEM_5;
    QCheckBox *CHb_pic12_WURE_5;
    QGroupBox *groupBox_30;
    QTextEdit *txtE_low_12;
    QLabel *label_32;
    QWidget *page_4;
    QGroupBox *groupBox_14;
    QGroupBox *groupBox_16;
    QCheckBox *CHb_pic12_BOR0;
    QCheckBox *CHb_pic12_BOR1;
    QCheckBox *CHb_pic12_BOR2;
    QCheckBox *CHb_pic12_POR2;
    QCheckBox *CHb_pic12_POR0;
    QCheckBox *CHb_pic12_POR1;
    QCheckBox *CHb_pic12_fcalo;
    QCheckBox *CHb_pic12_fcalo1;
    QCheckBox *CHb_pic12_fcalo2;
    QCheckBox *CHb_pic12_fcalo3;
    QCheckBox *CHb_pic12_fcalo6;
    QCheckBox *CHb_pic12_fcalo5;
    QCheckBox *CHb_pic12_fcalo4;
    QCheckBox *CHb_pic12_lvd0;
    QCheckBox *CHb_pic12_lvd1;
    QCheckBox *CHb_pic12_lvd2;
    QCheckBox *CHb_pic12_WUR0;
    QCheckBox *CHb_pic12_WUR2;
    QCheckBox *CHb_pic12_WUR3;
    QLabel *label_14;
    QLabel *label_pic12_2008;
    QLabel *label_18;
    QLabel *label_pic12_2009;
    QCheckBox *CHb_pic12_update_cal;
    QGroupBox *groupBox_17;
    QRadioButton *Rd_pi12_lp_2;
    QRadioButton *Rd_pi12_xt_2;
    QRadioButton *Rd_pi12_hs_2;
    QRadioButton *Rd_pi12_ec_io_2;
    QRadioButton *Rd_pi12_osc_io_2;
    QRadioButton *Rd_pi12_osc_clkout_2;
    QRadioButton *Rd_pi12_rc_io_2;
    QRadioButton *Rd_pi12_rc_6;
    QCheckBox *CHb_pic12_BODEN1;
    QCheckBox *CHb_pic12_wdt_3;
    QCheckBox *CHb_pic12_CP_2;
    QCheckBox *CHb_pic12_BODEN0;
    QCheckBox *CHb_pic12_pwrte_2;
    QCheckBox *CHb_pic12_cpd_2;
    QCheckBox *CHb_pic12_boden_2;
    QLabel *label_13;
    QLabel *label_pic12_2007;
    QCheckBox *CHb_pic12_IESO;
    QCheckBox *CHb_pic12_FCMEM;
    QCheckBox *CHb_pic12_WURE;
    QGroupBox *groupBox_18;
    QTextEdit *txtE_low_8;
    QLabel *label_15;
    QWidget *page_5;
    QGroupBox *groupBox_19;
    QGroupBox *groupBox_22;
    QCheckBox *CHb_pic12_BOR0_3;
    QCheckBox *CHb_pic12_BOR1_3;
    QCheckBox *CHb_pic12_BOR2_3;
    QCheckBox *CHb_pic12_POR0_3;
    QCheckBox *CHb_pic12_POR1_3;
    QCheckBox *CHb_pic12_fcalo_3;
    QCheckBox *CHb_pic12_fcalo1_3;
    QCheckBox *CHb_pic12_fcalo2_3;
    QCheckBox *CHb_pic12_fcalo3_3;
    QCheckBox *CHb_pic12_fcalo6_3;
    QCheckBox *CHb_pic12_fcalo5_3;
    QCheckBox *CHb_pic12_fcalo4_3;
    QCheckBox *CHb_pic12_lvd0_3;
    QCheckBox *CHb_pic12_lvd1_3;
    QCheckBox *CHb_pic12_lvd2_3;
    QLabel *label_21;
    QLabel *label_pic12_2013;
    QLabel *label_22;
    QLabel *label_pic12_2014;
    QCheckBox *CHb_pic12_update_cal_3;
    QGroupBox *groupBox_23;
    QRadioButton *Rd_pi12_lp_4;
    QRadioButton *Rd_pi12_xt_4;
    QRadioButton *Rd_pi12_hs_4;
    QRadioButton *Rd_pi12_ec_io_4;
    QRadioButton *Rd_pi12_osc_io_4;
    QRadioButton *Rd_pi12_osc_clkout_4;
    QRadioButton *Rd_pi12_rc_io_4;
    QRadioButton *Rd_pi12_rc_8;
    QCheckBox *CHb_pic12_BODEN1_3;
    QCheckBox *CHb_pic12_wdt_5;
    QCheckBox *CHb_pic12_CP_4;
    QCheckBox *CHb_pic12_BODEN0_3;
    QCheckBox *CHb_pic12_pwrte_4;
    QCheckBox *CHb_pic12_cpd_4;
    QCheckBox *CHb_pic12_boden_4;
    QLabel *label_23;
    QLabel *label_pic12_2015;
    QCheckBox *CHb_pic12_IESO_3;
    QCheckBox *CHb_pic12_FCMEM_3;
    QCheckBox *CHb_pic12_WURE_3;
    QGroupBox *groupBox_24;
    QTextEdit *txtE_low_10;
    QLabel *label_24;
    QWidget *page_8;
    QGroupBox *groupBox_20;
    QCheckBox *CHb_pic12_BODEN1_2;
    QCheckBox *CHb_pic12_wdt_4;
    QCheckBox *CHb_pic12_CP_3;
    QCheckBox *CHb_pic12_BODEN0_2;
    QCheckBox *CHb_pic12_pwrte_3;
    QCheckBox *CHb_pic12_cpd_3;
    QCheckBox *CHb_pic12_boden_3;
    QLabel *label_16;
    QLabel *label_pic12_2010;
    QCheckBox *CHb_pic12_IESO_2;
    QCheckBox *CHb_pic12_FCMEM_2;
    QCheckBox *CHb_pic12_WURE_2;
    PicFuseSettings *pagePicFuseSettings;
    AvrFuseSettings *pageAvrFuseSettings;
    QGridLayout *gridLayout_2;
    QWidget *page_6;
    QGroupBox *groupBox_12;
    QTextEdit *txtE_low_8_10f;
    QLabel *label_11_10f;
    QGroupBox *groupBox_13;
    QCheckBox *CHb_pic10_wdt;
    QCheckBox *CHb_pic10_boden;
    QCheckBox *CHb_pic10_CP;
    QLabel *label_11;
    QLabel *label_12;
    QGroupBox *groupBox_15;
    QTextEdit *txtE_low_8_10f_osc;
    QLabel *label_11_10f_osc;

    void setupUi(QWidget *FuseSettings)
    {
        if (FuseSettings->objectName().isEmpty())
            FuseSettings->setObjectName(QString::fromUtf8("FuseSettings"));
        FuseSettings->resize(676, 325);
        gridLayout = new QGridLayout(FuseSettings);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        stackedWidget = new QStackedWidget(FuseSettings);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        groupBox_4 = new QGroupBox(page);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(510, 190, 131, 80));
        txtE_low_6 = new QTextEdit(groupBox_4);
        txtE_low_6->setObjectName(QString::fromUtf8("txtE_low_6"));
        txtE_low_6->setEnabled(true);
        txtE_low_6->setGeometry(QRect(30, 20, 51, 21));
#if QT_CONFIG(whatsthis)
        txtE_low_6->setWhatsThis(QString::fromUtf8(""));
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        txtE_low_6->setAccessibleName(QString::fromUtf8(""));
#endif // QT_CONFIG(accessibility)
        txtE_low_6->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txtE_low_6->setUndoRedoEnabled(false);
        txtE_low_6->setOverwriteMode(true);
        txtE_low_6->setTabStopWidth(2);
        txtE_low_6->setAcceptRichText(true);
        label_5 = new QLabel(groupBox_4);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 50, 101, 20));
        QPalette palette;
        QBrush brush(QColor(0, 0, 127, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(118, 116, 108, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_5->setPalette(palette);
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        label_5->setFont(font);
        label_5->setFocusPolicy(Qt::ClickFocus);
        label_5->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_5->setFrameShadow(QFrame::Raised);
        label_5->setLineWidth(2);
        groupBox_5 = new QGroupBox(page);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(50, 10, 371, 271));
        CHb_pic12_wdt = new QCheckBox(groupBox_5);
        CHb_pic12_wdt->setObjectName(QString::fromUtf8("CHb_pic12_wdt"));
        CHb_pic12_wdt->setGeometry(QRect(180, 170, 70, 17));
        CHb_pic12_pwrte = new QCheckBox(groupBox_5);
        CHb_pic12_pwrte->setObjectName(QString::fromUtf8("CHb_pic12_pwrte"));
        CHb_pic12_pwrte->setGeometry(QRect(180, 190, 70, 17));
        CHb_pic12_boden = new QCheckBox(groupBox_5);
        CHb_pic12_boden->setObjectName(QString::fromUtf8("CHb_pic12_boden"));
        CHb_pic12_boden->setGeometry(QRect(180, 210, 70, 17));
        CHb_pic12_wdt_2 = new QCheckBox(groupBox_5);
        CHb_pic12_wdt_2->setObjectName(QString::fromUtf8("CHb_pic12_wdt_2"));
        CHb_pic12_wdt_2->setGeometry(QRect(270, 170, 70, 17));
        CHb_pic12_cpd = new QCheckBox(groupBox_5);
        CHb_pic12_cpd->setObjectName(QString::fromUtf8("CHb_pic12_cpd"));
        CHb_pic12_cpd->setGeometry(QRect(270, 190, 70, 17));
        CHb_pic12_CP = new QCheckBox(groupBox_5);
        CHb_pic12_CP->setObjectName(QString::fromUtf8("CHb_pic12_CP"));
        CHb_pic12_CP->setGeometry(QRect(270, 210, 70, 17));
        label_6 = new QLabel(groupBox_5);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(250, 240, 61, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_6->setPalette(palette1);
        label_6->setFont(font);
        label_6->setFocusPolicy(Qt::ClickFocus);
        label_6->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_6->setFrameShadow(QFrame::Raised);
        label_6->setLineWidth(2);
        label_7 = new QLabel(groupBox_5);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(320, 240, 46, 21));
        label_7->setFont(font);
        groupBox_6 = new QGroupBox(groupBox_5);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(160, 40, 161, 111));
        Rd_pi12_03 = new QRadioButton(groupBox_6);
        Rd_pi12_03->setObjectName(QString::fromUtf8("Rd_pi12_03"));
        Rd_pi12_03->setGeometry(QRect(20, 20, 101, 17));
        Rd_pi16_pof_2 = new QRadioButton(groupBox_6);
        Rd_pi16_pof_2->setObjectName(QString::fromUtf8("Rd_pi16_pof_2"));
        Rd_pi16_pof_2->setGeometry(QRect(20, 40, 121, 17));
        Rd_pi16_pof_3 = new QRadioButton(groupBox_6);
        Rd_pi16_pof_3->setObjectName(QString::fromUtf8("Rd_pi16_pof_3"));
        Rd_pi16_pof_3->setGeometry(QRect(20, 60, 101, 17));
        Rd_pi16_00 = new QRadioButton(groupBox_6);
        Rd_pi16_00->setObjectName(QString::fromUtf8("Rd_pi16_00"));
        Rd_pi16_00->setGeometry(QRect(20, 80, 101, 17));
        groupBox_7 = new QGroupBox(groupBox_5);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(20, 40, 121, 191));
        Rd_pi12_lp = new QRadioButton(groupBox_7);
        Rd_pi12_lp->setObjectName(QString::fromUtf8("Rd_pi12_lp"));
        Rd_pi12_lp->setGeometry(QRect(10, 20, 82, 17));
        Rd_pi12_xt = new QRadioButton(groupBox_7);
        Rd_pi12_xt->setObjectName(QString::fromUtf8("Rd_pi12_xt"));
        Rd_pi12_xt->setGeometry(QRect(10, 40, 81, 20));
        Rd_pi12_hs = new QRadioButton(groupBox_7);
        Rd_pi12_hs->setObjectName(QString::fromUtf8("Rd_pi12_hs"));
        Rd_pi12_hs->setGeometry(QRect(10, 60, 82, 17));
        Rd_pi12_ec_io = new QRadioButton(groupBox_7);
        Rd_pi12_ec_io->setObjectName(QString::fromUtf8("Rd_pi12_ec_io"));
        Rd_pi12_ec_io->setGeometry(QRect(10, 80, 82, 17));
        Rd_pi12_osc_io = new QRadioButton(groupBox_7);
        Rd_pi12_osc_io->setObjectName(QString::fromUtf8("Rd_pi12_osc_io"));
        Rd_pi12_osc_io->setGeometry(QRect(10, 100, 82, 17));
        Rd_pi12_osc_clkout = new QRadioButton(groupBox_7);
        Rd_pi12_osc_clkout->setObjectName(QString::fromUtf8("Rd_pi12_osc_clkout"));
        Rd_pi12_osc_clkout->setGeometry(QRect(10, 120, 101, 17));
        Rd_pi12_rc_io = new QRadioButton(groupBox_7);
        Rd_pi12_rc_io->setObjectName(QString::fromUtf8("Rd_pi12_rc_io"));
        Rd_pi12_rc_io->setGeometry(QRect(10, 140, 82, 17));
        Rd_pi12_rc_5 = new QRadioButton(groupBox_7);
        Rd_pi12_rc_5->setObjectName(QString::fromUtf8("Rd_pi12_rc_5"));
        Rd_pi12_rc_5->setGeometry(QRect(10, 160, 82, 17));
        stackedWidget->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        groupBox_8 = new QGroupBox(page_3);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(50, 20, 311, 251));
        CHb_pic16_wdt_3 = new QCheckBox(groupBox_8);
        CHb_pic16_wdt_3->setObjectName(QString::fromUtf8("CHb_pic16_wdt_3"));
        CHb_pic16_wdt_3->setGeometry(QRect(30, 160, 70, 17));
        CHb_pic16_pwrte_2 = new QCheckBox(groupBox_8);
        CHb_pic16_pwrte_2->setObjectName(QString::fromUtf8("CHb_pic16_pwrte_2"));
        CHb_pic16_pwrte_2->setGeometry(QRect(30, 180, 70, 17));
        CHb_pic16_boden_2 = new QCheckBox(groupBox_8);
        CHb_pic16_boden_2->setObjectName(QString::fromUtf8("CHb_pic16_boden_2"));
        CHb_pic16_boden_2->setGeometry(QRect(30, 200, 70, 17));
        CHb_pic16_wdt_4 = new QCheckBox(groupBox_8);
        CHb_pic16_wdt_4->setObjectName(QString::fromUtf8("CHb_pic16_wdt_4"));
        CHb_pic16_wdt_4->setGeometry(QRect(120, 160, 70, 17));
        CHb_pic16_cpd_2 = new QCheckBox(groupBox_8);
        CHb_pic16_cpd_2->setObjectName(QString::fromUtf8("CHb_pic16_cpd_2"));
        CHb_pic16_cpd_2->setGeometry(QRect(120, 180, 70, 17));
        CHb_pic16_CP_2 = new QCheckBox(groupBox_8);
        CHb_pic16_CP_2->setObjectName(QString::fromUtf8("CHb_pic16_CP_2"));
        CHb_pic16_CP_2->setGeometry(QRect(120, 200, 70, 17));
        label_8 = new QLabel(groupBox_8);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(200, 210, 61, 20));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_8->setPalette(palette2);
        label_8->setFont(font);
        label_8->setFocusPolicy(Qt::ClickFocus);
        label_8->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_8->setFrameShadow(QFrame::Raised);
        label_8->setLineWidth(2);
        label_9 = new QLabel(groupBox_8);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(260, 210, 46, 21));
        label_9->setFont(font);
        groupBox_9 = new QGroupBox(groupBox_8);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(120, 40, 131, 101));
        Rd_pi16_pof_5 = new QRadioButton(groupBox_9);
        Rd_pi16_pof_5->setObjectName(QString::fromUtf8("Rd_pi16_pof_5"));
        Rd_pi16_pof_5->setGeometry(QRect(10, 10, 82, 17));
        Rd_pi16_pof_6 = new QRadioButton(groupBox_9);
        Rd_pi16_pof_6->setObjectName(QString::fromUtf8("Rd_pi16_pof_6"));
        Rd_pi16_pof_6->setGeometry(QRect(10, 30, 101, 17));
        Rd_pi16_pof_7 = new QRadioButton(groupBox_9);
        Rd_pi16_pof_7->setObjectName(QString::fromUtf8("Rd_pi16_pof_7"));
        Rd_pi16_pof_7->setGeometry(QRect(10, 50, 91, 17));
        Rd_pi16_pof_8 = new QRadioButton(groupBox_9);
        Rd_pi16_pof_8->setObjectName(QString::fromUtf8("Rd_pi16_pof_8"));
        Rd_pi16_pof_8->setGeometry(QRect(10, 70, 91, 17));
        groupBox_10 = new QGroupBox(groupBox_8);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(20, 30, 71, 111));
        Rd_pi16_lp_2 = new QRadioButton(groupBox_10);
        Rd_pi16_lp_2->setObjectName(QString::fromUtf8("Rd_pi16_lp_2"));
        Rd_pi16_lp_2->setGeometry(QRect(10, 20, 82, 17));
        Rd_pi16_xt_2 = new QRadioButton(groupBox_10);
        Rd_pi16_xt_2->setObjectName(QString::fromUtf8("Rd_pi16_xt_2"));
        Rd_pi16_xt_2->setGeometry(QRect(10, 40, 82, 17));
        Rd_pi16_hs_2 = new QRadioButton(groupBox_10);
        Rd_pi16_hs_2->setObjectName(QString::fromUtf8("Rd_pi16_hs_2"));
        Rd_pi16_hs_2->setGeometry(QRect(10, 60, 82, 17));
        Rd_pi16_rc_2 = new QRadioButton(groupBox_10);
        Rd_pi16_rc_2->setObjectName(QString::fromUtf8("Rd_pi16_rc_2"));
        Rd_pi16_rc_2->setGeometry(QRect(10, 80, 82, 17));
        CHb_pic16_debug_2 = new QCheckBox(groupBox_8);
        CHb_pic16_debug_2->setObjectName(QString::fromUtf8("CHb_pic16_debug_2"));
        CHb_pic16_debug_2->setGeometry(QRect(200, 180, 70, 17));
        groupBox_11 = new QGroupBox(page_3);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(500, 190, 131, 80));
        txtE_low_7 = new QTextEdit(groupBox_11);
        txtE_low_7->setObjectName(QString::fromUtf8("txtE_low_7"));
        txtE_low_7->setEnabled(true);
        txtE_low_7->setGeometry(QRect(30, 20, 51, 21));
#if QT_CONFIG(whatsthis)
        txtE_low_7->setWhatsThis(QString::fromUtf8(""));
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        txtE_low_7->setAccessibleName(QString::fromUtf8(""));
#endif // QT_CONFIG(accessibility)
        txtE_low_7->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txtE_low_7->setUndoRedoEnabled(false);
        txtE_low_7->setOverwriteMode(true);
        txtE_low_7->setTabStopWidth(2);
        txtE_low_7->setAcceptRichText(true);
        label_10 = new QLabel(groupBox_11);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(20, 50, 101, 20));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_10->setPalette(palette3);
        label_10->setFont(font);
        label_10->setFocusPolicy(Qt::ClickFocus);
        label_10->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_10->setFrameShadow(QFrame::Raised);
        label_10->setLineWidth(2);
        stackedWidget->addWidget(page_3);
        page_7 = new QWidget();
        page_7->setObjectName(QString::fromUtf8("page_7"));
        groupBox_25 = new QGroupBox(page_7);
        groupBox_25->setObjectName(QString::fromUtf8("groupBox_25"));
        groupBox_25->setGeometry(QRect(20, 10, 491, 291));
        groupBox_28 = new QGroupBox(groupBox_25);
        groupBox_28->setObjectName(QString::fromUtf8("groupBox_28"));
        groupBox_28->setGeometry(QRect(230, 30, 241, 251));
        CHb_pic12_BOR0_5 = new QCheckBox(groupBox_28);
        CHb_pic12_BOR0_5->setObjectName(QString::fromUtf8("CHb_pic12_BOR0_5"));
        CHb_pic12_BOR0_5->setGeometry(QRect(20, 30, 70, 17));
        CHb_pic12_BOR1_5 = new QCheckBox(groupBox_28);
        CHb_pic12_BOR1_5->setObjectName(QString::fromUtf8("CHb_pic12_BOR1_5"));
        CHb_pic12_BOR1_5->setGeometry(QRect(20, 50, 71, 20));
        CHb_pic12_BOR2_5 = new QCheckBox(groupBox_28);
        CHb_pic12_BOR2_5->setObjectName(QString::fromUtf8("CHb_pic12_BOR2_5"));
        CHb_pic12_BOR2_5->setGeometry(QRect(20, 70, 70, 17));
        CHb_pic12_POR2_4 = new QCheckBox(groupBox_28);
        CHb_pic12_POR2_4->setObjectName(QString::fromUtf8("CHb_pic12_POR2_4"));
        CHb_pic12_POR2_4->setGeometry(QRect(90, 70, 70, 17));
        CHb_pic12_POR0_5 = new QCheckBox(groupBox_28);
        CHb_pic12_POR0_5->setObjectName(QString::fromUtf8("CHb_pic12_POR0_5"));
        CHb_pic12_POR0_5->setGeometry(QRect(90, 30, 70, 17));
        CHb_pic12_POR1_5 = new QCheckBox(groupBox_28);
        CHb_pic12_POR1_5->setObjectName(QString::fromUtf8("CHb_pic12_POR1_5"));
        CHb_pic12_POR1_5->setGeometry(QRect(90, 50, 71, 20));
        CHb_pic12_fcalo_5 = new QCheckBox(groupBox_28);
        CHb_pic12_fcalo_5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo_5"));
        CHb_pic12_fcalo_5->setGeometry(QRect(20, 100, 70, 17));
        CHb_pic12_fcalo1_5 = new QCheckBox(groupBox_28);
        CHb_pic12_fcalo1_5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo1_5"));
        CHb_pic12_fcalo1_5->setGeometry(QRect(20, 120, 70, 17));
        CHb_pic12_fcalo2_5 = new QCheckBox(groupBox_28);
        CHb_pic12_fcalo2_5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo2_5"));
        CHb_pic12_fcalo2_5->setGeometry(QRect(20, 140, 70, 17));
        CHb_pic12_fcalo3_5 = new QCheckBox(groupBox_28);
        CHb_pic12_fcalo3_5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo3_5"));
        CHb_pic12_fcalo3_5->setGeometry(QRect(20, 160, 70, 17));
        CHb_pic12_fcalo6_5 = new QCheckBox(groupBox_28);
        CHb_pic12_fcalo6_5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo6_5"));
        CHb_pic12_fcalo6_5->setGeometry(QRect(20, 220, 70, 17));
        CHb_pic12_fcalo5_5 = new QCheckBox(groupBox_28);
        CHb_pic12_fcalo5_5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo5_5"));
        CHb_pic12_fcalo5_5->setGeometry(QRect(20, 200, 70, 17));
        CHb_pic12_fcalo4_5 = new QCheckBox(groupBox_28);
        CHb_pic12_fcalo4_5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo4_5"));
        CHb_pic12_fcalo4_5->setGeometry(QRect(20, 180, 70, 17));
        label_29 = new QLabel(groupBox_28);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(120, 170, 61, 20));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_29->setPalette(palette4);
        label_29->setFont(font);
        label_29->setFocusPolicy(Qt::ClickFocus);
        label_29->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_29->setFrameShadow(QFrame::Raised);
        label_29->setLineWidth(2);
        label_pic12_2019 = new QLabel(groupBox_28);
        label_pic12_2019->setObjectName(QString::fromUtf8("label_pic12_2019"));
        label_pic12_2019->setGeometry(QRect(180, 170, 46, 21));
        label_pic12_2019->setFont(font);
        CHb_pic12_update_cal_5 = new QCheckBox(groupBox_28);
        CHb_pic12_update_cal_5->setObjectName(QString::fromUtf8("CHb_pic12_update_cal_5"));
        CHb_pic12_update_cal_5->setGeometry(QRect(90, 220, 131, 17));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        CHb_pic12_update_cal_5->setFont(font1);
        CHb_pic12_update_cal_5->setAcceptDrops(true);
        groupBox_29 = new QGroupBox(groupBox_25);
        groupBox_29->setObjectName(QString::fromUtf8("groupBox_29"));
        groupBox_29->setGeometry(QRect(20, 30, 201, 251));
        Rd_pi12_lp_6 = new QRadioButton(groupBox_29);
        Rd_pi12_lp_6->setObjectName(QString::fromUtf8("Rd_pi12_lp_6"));
        Rd_pi12_lp_6->setGeometry(QRect(10, 20, 82, 17));
        Rd_pi12_xt_6 = new QRadioButton(groupBox_29);
        Rd_pi12_xt_6->setObjectName(QString::fromUtf8("Rd_pi12_xt_6"));
        Rd_pi12_xt_6->setGeometry(QRect(10, 40, 81, 20));
        Rd_pi12_hs_6 = new QRadioButton(groupBox_29);
        Rd_pi12_hs_6->setObjectName(QString::fromUtf8("Rd_pi12_hs_6"));
        Rd_pi12_hs_6->setGeometry(QRect(10, 60, 82, 17));
        Rd_pi12_ec_io_6 = new QRadioButton(groupBox_29);
        Rd_pi12_ec_io_6->setObjectName(QString::fromUtf8("Rd_pi12_ec_io_6"));
        Rd_pi12_ec_io_6->setGeometry(QRect(10, 80, 82, 17));
        Rd_pi12_osc_io_6 = new QRadioButton(groupBox_29);
        Rd_pi12_osc_io_6->setObjectName(QString::fromUtf8("Rd_pi12_osc_io_6"));
        Rd_pi12_osc_io_6->setGeometry(QRect(10, 100, 82, 17));
        Rd_pi12_osc_clkout_6 = new QRadioButton(groupBox_29);
        Rd_pi12_osc_clkout_6->setObjectName(QString::fromUtf8("Rd_pi12_osc_clkout_6"));
        Rd_pi12_osc_clkout_6->setGeometry(QRect(10, 120, 101, 17));
        Rd_pi12_rc_io_6 = new QRadioButton(groupBox_29);
        Rd_pi12_rc_io_6->setObjectName(QString::fromUtf8("Rd_pi12_rc_io_6"));
        Rd_pi12_rc_io_6->setGeometry(QRect(10, 140, 82, 17));
        Rd_pi12_rc_10 = new QRadioButton(groupBox_29);
        Rd_pi12_rc_10->setObjectName(QString::fromUtf8("Rd_pi12_rc_10"));
        Rd_pi12_rc_10->setGeometry(QRect(10, 160, 82, 17));
        CHb_pic12_BODEN1_5 = new QCheckBox(groupBox_29);
        CHb_pic12_BODEN1_5->setObjectName(QString::fromUtf8("CHb_pic12_BODEN1_5"));
        CHb_pic12_BODEN1_5->setGeometry(QRect(120, 130, 70, 17));
        CHb_pic12_wdt_7 = new QCheckBox(groupBox_29);
        CHb_pic12_wdt_7->setObjectName(QString::fromUtf8("CHb_pic12_wdt_7"));
        CHb_pic12_wdt_7->setGeometry(QRect(120, 10, 70, 17));
        CHb_pic12_CP_6 = new QCheckBox(groupBox_29);
        CHb_pic12_CP_6->setObjectName(QString::fromUtf8("CHb_pic12_CP_6"));
        CHb_pic12_CP_6->setGeometry(QRect(120, 70, 70, 17));
        CHb_pic12_BODEN0_5 = new QCheckBox(groupBox_29);
        CHb_pic12_BODEN0_5->setObjectName(QString::fromUtf8("CHb_pic12_BODEN0_5"));
        CHb_pic12_BODEN0_5->setGeometry(QRect(120, 110, 70, 17));
        CHb_pic12_pwrte_6 = new QCheckBox(groupBox_29);
        CHb_pic12_pwrte_6->setObjectName(QString::fromUtf8("CHb_pic12_pwrte_6"));
        CHb_pic12_pwrte_6->setGeometry(QRect(120, 30, 70, 17));
        CHb_pic12_cpd_6 = new QCheckBox(groupBox_29);
        CHb_pic12_cpd_6->setObjectName(QString::fromUtf8("CHb_pic12_cpd_6"));
        CHb_pic12_cpd_6->setGeometry(QRect(120, 90, 70, 17));
        CHb_pic12_boden_6 = new QCheckBox(groupBox_29);
        CHb_pic12_boden_6->setObjectName(QString::fromUtf8("CHb_pic12_boden_6"));
        CHb_pic12_boden_6->setGeometry(QRect(120, 50, 70, 17));
        label_31 = new QLabel(groupBox_29);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 210, 61, 20));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_31->setPalette(palette5);
        label_31->setFont(font);
        label_31->setFocusPolicy(Qt::ClickFocus);
        label_31->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_31->setFrameShadow(QFrame::Raised);
        label_31->setLineWidth(2);
        label_pic12_2021 = new QLabel(groupBox_29);
        label_pic12_2021->setObjectName(QString::fromUtf8("label_pic12_2021"));
        label_pic12_2021->setGeometry(QRect(70, 210, 46, 21));
        label_pic12_2021->setFont(font);
        CHb_pic12_IESO_5 = new QCheckBox(groupBox_29);
        CHb_pic12_IESO_5->setObjectName(QString::fromUtf8("CHb_pic12_IESO_5"));
        CHb_pic12_IESO_5->setGeometry(QRect(120, 150, 70, 17));
        CHb_pic12_FCMEM_5 = new QCheckBox(groupBox_29);
        CHb_pic12_FCMEM_5->setObjectName(QString::fromUtf8("CHb_pic12_FCMEM_5"));
        CHb_pic12_FCMEM_5->setGeometry(QRect(120, 170, 70, 17));
        CHb_pic12_WURE_5 = new QCheckBox(groupBox_29);
        CHb_pic12_WURE_5->setObjectName(QString::fromUtf8("CHb_pic12_WURE_5"));
        CHb_pic12_WURE_5->setGeometry(QRect(120, 190, 70, 17));
        groupBox_30 = new QGroupBox(page_7);
        groupBox_30->setObjectName(QString::fromUtf8("groupBox_30"));
        groupBox_30->setGeometry(QRect(520, 220, 131, 80));
        txtE_low_12 = new QTextEdit(groupBox_30);
        txtE_low_12->setObjectName(QString::fromUtf8("txtE_low_12"));
        txtE_low_12->setEnabled(true);
        txtE_low_12->setGeometry(QRect(30, 20, 51, 21));
#if QT_CONFIG(whatsthis)
        txtE_low_12->setWhatsThis(QString::fromUtf8(""));
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        txtE_low_12->setAccessibleName(QString::fromUtf8(""));
#endif // QT_CONFIG(accessibility)
        txtE_low_12->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txtE_low_12->setUndoRedoEnabled(false);
        txtE_low_12->setOverwriteMode(true);
        txtE_low_12->setTabStopWidth(2);
        txtE_low_12->setAcceptRichText(true);
        label_32 = new QLabel(groupBox_30);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(20, 50, 101, 20));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_32->setPalette(palette6);
        label_32->setFont(font);
        label_32->setFocusPolicy(Qt::ClickFocus);
        label_32->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_32->setFrameShadow(QFrame::Raised);
        label_32->setLineWidth(2);
        stackedWidget->addWidget(page_7);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        groupBox_14 = new QGroupBox(page_4);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(20, 0, 491, 291));
        groupBox_16 = new QGroupBox(groupBox_14);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(230, 30, 241, 251));
        CHb_pic12_BOR0 = new QCheckBox(groupBox_16);
        CHb_pic12_BOR0->setObjectName(QString::fromUtf8("CHb_pic12_BOR0"));
        CHb_pic12_BOR0->setGeometry(QRect(20, 30, 70, 17));
        CHb_pic12_BOR1 = new QCheckBox(groupBox_16);
        CHb_pic12_BOR1->setObjectName(QString::fromUtf8("CHb_pic12_BOR1"));
        CHb_pic12_BOR1->setGeometry(QRect(20, 50, 71, 20));
        CHb_pic12_BOR2 = new QCheckBox(groupBox_16);
        CHb_pic12_BOR2->setObjectName(QString::fromUtf8("CHb_pic12_BOR2"));
        CHb_pic12_BOR2->setGeometry(QRect(20, 70, 70, 17));
        CHb_pic12_POR2 = new QCheckBox(groupBox_16);
        CHb_pic12_POR2->setObjectName(QString::fromUtf8("CHb_pic12_POR2"));
        CHb_pic12_POR2->setGeometry(QRect(90, 70, 70, 17));
        CHb_pic12_POR0 = new QCheckBox(groupBox_16);
        CHb_pic12_POR0->setObjectName(QString::fromUtf8("CHb_pic12_POR0"));
        CHb_pic12_POR0->setGeometry(QRect(90, 30, 70, 17));
        CHb_pic12_POR1 = new QCheckBox(groupBox_16);
        CHb_pic12_POR1->setObjectName(QString::fromUtf8("CHb_pic12_POR1"));
        CHb_pic12_POR1->setGeometry(QRect(90, 50, 71, 20));
        CHb_pic12_fcalo = new QCheckBox(groupBox_16);
        CHb_pic12_fcalo->setObjectName(QString::fromUtf8("CHb_pic12_fcalo"));
        CHb_pic12_fcalo->setGeometry(QRect(20, 100, 70, 17));
        CHb_pic12_fcalo1 = new QCheckBox(groupBox_16);
        CHb_pic12_fcalo1->setObjectName(QString::fromUtf8("CHb_pic12_fcalo1"));
        CHb_pic12_fcalo1->setGeometry(QRect(20, 120, 70, 17));
        CHb_pic12_fcalo2 = new QCheckBox(groupBox_16);
        CHb_pic12_fcalo2->setObjectName(QString::fromUtf8("CHb_pic12_fcalo2"));
        CHb_pic12_fcalo2->setGeometry(QRect(20, 140, 70, 17));
        CHb_pic12_fcalo3 = new QCheckBox(groupBox_16);
        CHb_pic12_fcalo3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo3"));
        CHb_pic12_fcalo3->setGeometry(QRect(20, 160, 70, 17));
        CHb_pic12_fcalo6 = new QCheckBox(groupBox_16);
        CHb_pic12_fcalo6->setObjectName(QString::fromUtf8("CHb_pic12_fcalo6"));
        CHb_pic12_fcalo6->setGeometry(QRect(20, 220, 70, 17));
        CHb_pic12_fcalo5 = new QCheckBox(groupBox_16);
        CHb_pic12_fcalo5->setObjectName(QString::fromUtf8("CHb_pic12_fcalo5"));
        CHb_pic12_fcalo5->setGeometry(QRect(20, 200, 70, 17));
        CHb_pic12_fcalo4 = new QCheckBox(groupBox_16);
        CHb_pic12_fcalo4->setObjectName(QString::fromUtf8("CHb_pic12_fcalo4"));
        CHb_pic12_fcalo4->setGeometry(QRect(20, 180, 70, 17));
        CHb_pic12_lvd0 = new QCheckBox(groupBox_16);
        CHb_pic12_lvd0->setObjectName(QString::fromUtf8("CHb_pic12_lvd0"));
        CHb_pic12_lvd0->setGeometry(QRect(160, 30, 70, 17));
        CHb_pic12_lvd1 = new QCheckBox(groupBox_16);
        CHb_pic12_lvd1->setObjectName(QString::fromUtf8("CHb_pic12_lvd1"));
        CHb_pic12_lvd1->setGeometry(QRect(160, 50, 70, 17));
        CHb_pic12_lvd2 = new QCheckBox(groupBox_16);
        CHb_pic12_lvd2->setObjectName(QString::fromUtf8("CHb_pic12_lvd2"));
        CHb_pic12_lvd2->setGeometry(QRect(160, 70, 70, 17));
        CHb_pic12_WUR0 = new QCheckBox(groupBox_16);
        CHb_pic12_WUR0->setObjectName(QString::fromUtf8("CHb_pic12_WUR0"));
        CHb_pic12_WUR0->setGeometry(QRect(100, 110, 70, 17));
        CHb_pic12_WUR2 = new QCheckBox(groupBox_16);
        CHb_pic12_WUR2->setObjectName(QString::fromUtf8("CHb_pic12_WUR2"));
        CHb_pic12_WUR2->setGeometry(QRect(100, 130, 70, 17));
        CHb_pic12_WUR3 = new QCheckBox(groupBox_16);
        CHb_pic12_WUR3->setObjectName(QString::fromUtf8("CHb_pic12_WUR3"));
        CHb_pic12_WUR3->setGeometry(QRect(100, 150, 70, 17));
        label_14 = new QLabel(groupBox_16);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(120, 170, 61, 20));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_14->setPalette(palette7);
        label_14->setFont(font);
        label_14->setFocusPolicy(Qt::ClickFocus);
        label_14->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_14->setFrameShadow(QFrame::Raised);
        label_14->setLineWidth(2);
        label_pic12_2008 = new QLabel(groupBox_16);
        label_pic12_2008->setObjectName(QString::fromUtf8("label_pic12_2008"));
        label_pic12_2008->setGeometry(QRect(180, 170, 46, 21));
        label_pic12_2008->setFont(font);
        label_18 = new QLabel(groupBox_16);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(120, 190, 61, 20));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_18->setPalette(palette8);
        label_18->setFont(font);
        label_18->setFocusPolicy(Qt::ClickFocus);
        label_18->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_18->setFrameShadow(QFrame::Raised);
        label_18->setLineWidth(2);
        label_pic12_2009 = new QLabel(groupBox_16);
        label_pic12_2009->setObjectName(QString::fromUtf8("label_pic12_2009"));
        label_pic12_2009->setGeometry(QRect(180, 190, 46, 21));
        label_pic12_2009->setFont(font);
        CHb_pic12_update_cal = new QCheckBox(groupBox_16);
        CHb_pic12_update_cal->setObjectName(QString::fromUtf8("CHb_pic12_update_cal"));
        CHb_pic12_update_cal->setGeometry(QRect(90, 220, 131, 17));
        CHb_pic12_update_cal->setFont(font1);
        CHb_pic12_update_cal->setAcceptDrops(true);
        groupBox_17 = new QGroupBox(groupBox_14);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(20, 30, 201, 251));
        Rd_pi12_lp_2 = new QRadioButton(groupBox_17);
        Rd_pi12_lp_2->setObjectName(QString::fromUtf8("Rd_pi12_lp_2"));
        Rd_pi12_lp_2->setGeometry(QRect(10, 20, 82, 17));
        Rd_pi12_xt_2 = new QRadioButton(groupBox_17);
        Rd_pi12_xt_2->setObjectName(QString::fromUtf8("Rd_pi12_xt_2"));
        Rd_pi12_xt_2->setGeometry(QRect(10, 40, 81, 20));
        Rd_pi12_hs_2 = new QRadioButton(groupBox_17);
        Rd_pi12_hs_2->setObjectName(QString::fromUtf8("Rd_pi12_hs_2"));
        Rd_pi12_hs_2->setGeometry(QRect(10, 60, 82, 17));
        Rd_pi12_ec_io_2 = new QRadioButton(groupBox_17);
        Rd_pi12_ec_io_2->setObjectName(QString::fromUtf8("Rd_pi12_ec_io_2"));
        Rd_pi12_ec_io_2->setGeometry(QRect(10, 80, 82, 17));
        Rd_pi12_osc_io_2 = new QRadioButton(groupBox_17);
        Rd_pi12_osc_io_2->setObjectName(QString::fromUtf8("Rd_pi12_osc_io_2"));
        Rd_pi12_osc_io_2->setGeometry(QRect(10, 100, 82, 17));
        Rd_pi12_osc_clkout_2 = new QRadioButton(groupBox_17);
        Rd_pi12_osc_clkout_2->setObjectName(QString::fromUtf8("Rd_pi12_osc_clkout_2"));
        Rd_pi12_osc_clkout_2->setGeometry(QRect(10, 120, 101, 17));
        Rd_pi12_rc_io_2 = new QRadioButton(groupBox_17);
        Rd_pi12_rc_io_2->setObjectName(QString::fromUtf8("Rd_pi12_rc_io_2"));
        Rd_pi12_rc_io_2->setGeometry(QRect(10, 140, 82, 17));
        Rd_pi12_rc_6 = new QRadioButton(groupBox_17);
        Rd_pi12_rc_6->setObjectName(QString::fromUtf8("Rd_pi12_rc_6"));
        Rd_pi12_rc_6->setGeometry(QRect(10, 160, 82, 17));
        CHb_pic12_BODEN1 = new QCheckBox(groupBox_17);
        CHb_pic12_BODEN1->setObjectName(QString::fromUtf8("CHb_pic12_BODEN1"));
        CHb_pic12_BODEN1->setGeometry(QRect(120, 130, 70, 17));
        CHb_pic12_wdt_3 = new QCheckBox(groupBox_17);
        CHb_pic12_wdt_3->setObjectName(QString::fromUtf8("CHb_pic12_wdt_3"));
        CHb_pic12_wdt_3->setGeometry(QRect(120, 10, 70, 17));
        CHb_pic12_CP_2 = new QCheckBox(groupBox_17);
        CHb_pic12_CP_2->setObjectName(QString::fromUtf8("CHb_pic12_CP_2"));
        CHb_pic12_CP_2->setGeometry(QRect(120, 70, 70, 17));
        CHb_pic12_BODEN0 = new QCheckBox(groupBox_17);
        CHb_pic12_BODEN0->setObjectName(QString::fromUtf8("CHb_pic12_BODEN0"));
        CHb_pic12_BODEN0->setGeometry(QRect(120, 110, 70, 17));
        CHb_pic12_pwrte_2 = new QCheckBox(groupBox_17);
        CHb_pic12_pwrte_2->setObjectName(QString::fromUtf8("CHb_pic12_pwrte_2"));
        CHb_pic12_pwrte_2->setGeometry(QRect(120, 30, 70, 17));
        CHb_pic12_cpd_2 = new QCheckBox(groupBox_17);
        CHb_pic12_cpd_2->setObjectName(QString::fromUtf8("CHb_pic12_cpd_2"));
        CHb_pic12_cpd_2->setGeometry(QRect(120, 90, 70, 17));
        CHb_pic12_boden_2 = new QCheckBox(groupBox_17);
        CHb_pic12_boden_2->setObjectName(QString::fromUtf8("CHb_pic12_boden_2"));
        CHb_pic12_boden_2->setGeometry(QRect(120, 50, 70, 17));
        label_13 = new QLabel(groupBox_17);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 210, 61, 20));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_13->setPalette(palette9);
        label_13->setFont(font);
        label_13->setFocusPolicy(Qt::ClickFocus);
        label_13->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_13->setFrameShadow(QFrame::Raised);
        label_13->setLineWidth(2);
        label_pic12_2007 = new QLabel(groupBox_17);
        label_pic12_2007->setObjectName(QString::fromUtf8("label_pic12_2007"));
        label_pic12_2007->setGeometry(QRect(70, 210, 46, 21));
        label_pic12_2007->setFont(font);
        CHb_pic12_IESO = new QCheckBox(groupBox_17);
        CHb_pic12_IESO->setObjectName(QString::fromUtf8("CHb_pic12_IESO"));
        CHb_pic12_IESO->setGeometry(QRect(120, 150, 70, 17));
        CHb_pic12_FCMEM = new QCheckBox(groupBox_17);
        CHb_pic12_FCMEM->setObjectName(QString::fromUtf8("CHb_pic12_FCMEM"));
        CHb_pic12_FCMEM->setGeometry(QRect(120, 170, 70, 17));
        CHb_pic12_WURE = new QCheckBox(groupBox_17);
        CHb_pic12_WURE->setObjectName(QString::fromUtf8("CHb_pic12_WURE"));
        CHb_pic12_WURE->setGeometry(QRect(120, 190, 70, 17));
        groupBox_18 = new QGroupBox(page_4);
        groupBox_18->setObjectName(QString::fromUtf8("groupBox_18"));
        groupBox_18->setGeometry(QRect(530, 210, 131, 80));
        txtE_low_8 = new QTextEdit(groupBox_18);
        txtE_low_8->setObjectName(QString::fromUtf8("txtE_low_8"));
        txtE_low_8->setEnabled(true);
        txtE_low_8->setGeometry(QRect(30, 20, 51, 21));
#if QT_CONFIG(whatsthis)
        txtE_low_8->setWhatsThis(QString::fromUtf8(""));
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        txtE_low_8->setAccessibleName(QString::fromUtf8(""));
#endif // QT_CONFIG(accessibility)
        txtE_low_8->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txtE_low_8->setUndoRedoEnabled(false);
        txtE_low_8->setOverwriteMode(true);
        txtE_low_8->setTabStopWidth(2);
        txtE_low_8->setAcceptRichText(true);
        label_15 = new QLabel(groupBox_18);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(20, 50, 101, 20));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_15->setPalette(palette10);
        label_15->setFont(font);
        label_15->setFocusPolicy(Qt::ClickFocus);
        label_15->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_15->setFrameShadow(QFrame::Raised);
        label_15->setLineWidth(2);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        groupBox_19 = new QGroupBox(page_5);
        groupBox_19->setObjectName(QString::fromUtf8("groupBox_19"));
        groupBox_19->setGeometry(QRect(80, 20, 491, 291));
        groupBox_22 = new QGroupBox(groupBox_19);
        groupBox_22->setObjectName(QString::fromUtf8("groupBox_22"));
        groupBox_22->setGeometry(QRect(230, 30, 241, 251));
        CHb_pic12_BOR0_3 = new QCheckBox(groupBox_22);
        CHb_pic12_BOR0_3->setObjectName(QString::fromUtf8("CHb_pic12_BOR0_3"));
        CHb_pic12_BOR0_3->setGeometry(QRect(20, 30, 70, 17));
        CHb_pic12_BOR1_3 = new QCheckBox(groupBox_22);
        CHb_pic12_BOR1_3->setObjectName(QString::fromUtf8("CHb_pic12_BOR1_3"));
        CHb_pic12_BOR1_3->setGeometry(QRect(20, 50, 71, 20));
        CHb_pic12_BOR2_3 = new QCheckBox(groupBox_22);
        CHb_pic12_BOR2_3->setObjectName(QString::fromUtf8("CHb_pic12_BOR2_3"));
        CHb_pic12_BOR2_3->setGeometry(QRect(20, 70, 70, 17));
        CHb_pic12_POR0_3 = new QCheckBox(groupBox_22);
        CHb_pic12_POR0_3->setObjectName(QString::fromUtf8("CHb_pic12_POR0_3"));
        CHb_pic12_POR0_3->setGeometry(QRect(90, 30, 70, 17));
        CHb_pic12_POR1_3 = new QCheckBox(groupBox_22);
        CHb_pic12_POR1_3->setObjectName(QString::fromUtf8("CHb_pic12_POR1_3"));
        CHb_pic12_POR1_3->setGeometry(QRect(90, 50, 71, 20));
        CHb_pic12_fcalo_3 = new QCheckBox(groupBox_22);
        CHb_pic12_fcalo_3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo_3"));
        CHb_pic12_fcalo_3->setGeometry(QRect(20, 100, 70, 17));
        CHb_pic12_fcalo1_3 = new QCheckBox(groupBox_22);
        CHb_pic12_fcalo1_3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo1_3"));
        CHb_pic12_fcalo1_3->setGeometry(QRect(20, 120, 70, 17));
        CHb_pic12_fcalo2_3 = new QCheckBox(groupBox_22);
        CHb_pic12_fcalo2_3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo2_3"));
        CHb_pic12_fcalo2_3->setGeometry(QRect(20, 140, 70, 17));
        CHb_pic12_fcalo3_3 = new QCheckBox(groupBox_22);
        CHb_pic12_fcalo3_3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo3_3"));
        CHb_pic12_fcalo3_3->setGeometry(QRect(20, 160, 70, 17));
        CHb_pic12_fcalo6_3 = new QCheckBox(groupBox_22);
        CHb_pic12_fcalo6_3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo6_3"));
        CHb_pic12_fcalo6_3->setGeometry(QRect(20, 220, 70, 17));
        CHb_pic12_fcalo5_3 = new QCheckBox(groupBox_22);
        CHb_pic12_fcalo5_3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo5_3"));
        CHb_pic12_fcalo5_3->setGeometry(QRect(20, 200, 70, 17));
        CHb_pic12_fcalo4_3 = new QCheckBox(groupBox_22);
        CHb_pic12_fcalo4_3->setObjectName(QString::fromUtf8("CHb_pic12_fcalo4_3"));
        CHb_pic12_fcalo4_3->setGeometry(QRect(20, 180, 70, 17));
        CHb_pic12_lvd0_3 = new QCheckBox(groupBox_22);
        CHb_pic12_lvd0_3->setObjectName(QString::fromUtf8("CHb_pic12_lvd0_3"));
        CHb_pic12_lvd0_3->setGeometry(QRect(160, 30, 70, 17));
        CHb_pic12_lvd1_3 = new QCheckBox(groupBox_22);
        CHb_pic12_lvd1_3->setObjectName(QString::fromUtf8("CHb_pic12_lvd1_3"));
        CHb_pic12_lvd1_3->setGeometry(QRect(160, 50, 70, 17));
        CHb_pic12_lvd2_3 = new QCheckBox(groupBox_22);
        CHb_pic12_lvd2_3->setObjectName(QString::fromUtf8("CHb_pic12_lvd2_3"));
        CHb_pic12_lvd2_3->setGeometry(QRect(160, 70, 70, 17));
        label_21 = new QLabel(groupBox_22);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(120, 170, 61, 20));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_21->setPalette(palette11);
        label_21->setFont(font);
        label_21->setFocusPolicy(Qt::ClickFocus);
        label_21->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_21->setFrameShadow(QFrame::Raised);
        label_21->setLineWidth(2);
        label_pic12_2013 = new QLabel(groupBox_22);
        label_pic12_2013->setObjectName(QString::fromUtf8("label_pic12_2013"));
        label_pic12_2013->setGeometry(QRect(180, 170, 46, 21));
        label_pic12_2013->setFont(font);
        label_22 = new QLabel(groupBox_22);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(120, 190, 61, 20));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_22->setPalette(palette12);
        label_22->setFont(font);
        label_22->setFocusPolicy(Qt::ClickFocus);
        label_22->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_22->setFrameShadow(QFrame::Raised);
        label_22->setLineWidth(2);
        label_pic12_2014 = new QLabel(groupBox_22);
        label_pic12_2014->setObjectName(QString::fromUtf8("label_pic12_2014"));
        label_pic12_2014->setGeometry(QRect(180, 190, 46, 21));
        label_pic12_2014->setFont(font);
        CHb_pic12_update_cal_3 = new QCheckBox(groupBox_22);
        CHb_pic12_update_cal_3->setObjectName(QString::fromUtf8("CHb_pic12_update_cal_3"));
        CHb_pic12_update_cal_3->setGeometry(QRect(90, 220, 131, 17));
        CHb_pic12_update_cal_3->setFont(font1);
        CHb_pic12_update_cal_3->setAcceptDrops(true);
        groupBox_23 = new QGroupBox(groupBox_19);
        groupBox_23->setObjectName(QString::fromUtf8("groupBox_23"));
        groupBox_23->setGeometry(QRect(20, 30, 201, 251));
        Rd_pi12_lp_4 = new QRadioButton(groupBox_23);
        Rd_pi12_lp_4->setObjectName(QString::fromUtf8("Rd_pi12_lp_4"));
        Rd_pi12_lp_4->setGeometry(QRect(10, 20, 82, 17));
        Rd_pi12_xt_4 = new QRadioButton(groupBox_23);
        Rd_pi12_xt_4->setObjectName(QString::fromUtf8("Rd_pi12_xt_4"));
        Rd_pi12_xt_4->setGeometry(QRect(10, 40, 81, 20));
        Rd_pi12_hs_4 = new QRadioButton(groupBox_23);
        Rd_pi12_hs_4->setObjectName(QString::fromUtf8("Rd_pi12_hs_4"));
        Rd_pi12_hs_4->setGeometry(QRect(10, 60, 82, 17));
        Rd_pi12_ec_io_4 = new QRadioButton(groupBox_23);
        Rd_pi12_ec_io_4->setObjectName(QString::fromUtf8("Rd_pi12_ec_io_4"));
        Rd_pi12_ec_io_4->setGeometry(QRect(10, 80, 82, 17));
        Rd_pi12_osc_io_4 = new QRadioButton(groupBox_23);
        Rd_pi12_osc_io_4->setObjectName(QString::fromUtf8("Rd_pi12_osc_io_4"));
        Rd_pi12_osc_io_4->setGeometry(QRect(10, 100, 82, 17));
        Rd_pi12_osc_clkout_4 = new QRadioButton(groupBox_23);
        Rd_pi12_osc_clkout_4->setObjectName(QString::fromUtf8("Rd_pi12_osc_clkout_4"));
        Rd_pi12_osc_clkout_4->setGeometry(QRect(10, 120, 101, 17));
        Rd_pi12_rc_io_4 = new QRadioButton(groupBox_23);
        Rd_pi12_rc_io_4->setObjectName(QString::fromUtf8("Rd_pi12_rc_io_4"));
        Rd_pi12_rc_io_4->setGeometry(QRect(10, 140, 82, 17));
        Rd_pi12_rc_8 = new QRadioButton(groupBox_23);
        Rd_pi12_rc_8->setObjectName(QString::fromUtf8("Rd_pi12_rc_8"));
        Rd_pi12_rc_8->setGeometry(QRect(10, 160, 82, 17));
        CHb_pic12_BODEN1_3 = new QCheckBox(groupBox_23);
        CHb_pic12_BODEN1_3->setObjectName(QString::fromUtf8("CHb_pic12_BODEN1_3"));
        CHb_pic12_BODEN1_3->setGeometry(QRect(120, 130, 70, 17));
        CHb_pic12_wdt_5 = new QCheckBox(groupBox_23);
        CHb_pic12_wdt_5->setObjectName(QString::fromUtf8("CHb_pic12_wdt_5"));
        CHb_pic12_wdt_5->setGeometry(QRect(120, 10, 70, 17));
        CHb_pic12_CP_4 = new QCheckBox(groupBox_23);
        CHb_pic12_CP_4->setObjectName(QString::fromUtf8("CHb_pic12_CP_4"));
        CHb_pic12_CP_4->setGeometry(QRect(120, 70, 70, 17));
        CHb_pic12_BODEN0_3 = new QCheckBox(groupBox_23);
        CHb_pic12_BODEN0_3->setObjectName(QString::fromUtf8("CHb_pic12_BODEN0_3"));
        CHb_pic12_BODEN0_3->setGeometry(QRect(120, 110, 70, 17));
        CHb_pic12_pwrte_4 = new QCheckBox(groupBox_23);
        CHb_pic12_pwrte_4->setObjectName(QString::fromUtf8("CHb_pic12_pwrte_4"));
        CHb_pic12_pwrte_4->setGeometry(QRect(120, 30, 70, 17));
        CHb_pic12_cpd_4 = new QCheckBox(groupBox_23);
        CHb_pic12_cpd_4->setObjectName(QString::fromUtf8("CHb_pic12_cpd_4"));
        CHb_pic12_cpd_4->setGeometry(QRect(120, 90, 70, 17));
        CHb_pic12_boden_4 = new QCheckBox(groupBox_23);
        CHb_pic12_boden_4->setObjectName(QString::fromUtf8("CHb_pic12_boden_4"));
        CHb_pic12_boden_4->setGeometry(QRect(120, 50, 70, 17));
        label_23 = new QLabel(groupBox_23);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 210, 61, 20));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_23->setPalette(palette13);
        label_23->setFont(font);
        label_23->setFocusPolicy(Qt::ClickFocus);
        label_23->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_23->setFrameShadow(QFrame::Raised);
        label_23->setLineWidth(2);
        label_pic12_2015 = new QLabel(groupBox_23);
        label_pic12_2015->setObjectName(QString::fromUtf8("label_pic12_2015"));
        label_pic12_2015->setGeometry(QRect(70, 210, 46, 21));
        label_pic12_2015->setFont(font);
        CHb_pic12_IESO_3 = new QCheckBox(groupBox_23);
        CHb_pic12_IESO_3->setObjectName(QString::fromUtf8("CHb_pic12_IESO_3"));
        CHb_pic12_IESO_3->setGeometry(QRect(120, 150, 70, 17));
        CHb_pic12_FCMEM_3 = new QCheckBox(groupBox_23);
        CHb_pic12_FCMEM_3->setObjectName(QString::fromUtf8("CHb_pic12_FCMEM_3"));
        CHb_pic12_FCMEM_3->setGeometry(QRect(120, 170, 70, 17));
        CHb_pic12_WURE_3 = new QCheckBox(groupBox_23);
        CHb_pic12_WURE_3->setObjectName(QString::fromUtf8("CHb_pic12_WURE_3"));
        CHb_pic12_WURE_3->setGeometry(QRect(120, 190, 70, 17));
        groupBox_24 = new QGroupBox(page_5);
        groupBox_24->setObjectName(QString::fromUtf8("groupBox_24"));
        groupBox_24->setGeometry(QRect(590, 230, 131, 80));
        txtE_low_10 = new QTextEdit(groupBox_24);
        txtE_low_10->setObjectName(QString::fromUtf8("txtE_low_10"));
        txtE_low_10->setEnabled(true);
        txtE_low_10->setGeometry(QRect(30, 20, 51, 21));
#if QT_CONFIG(whatsthis)
        txtE_low_10->setWhatsThis(QString::fromUtf8(""));
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        txtE_low_10->setAccessibleName(QString::fromUtf8(""));
#endif // QT_CONFIG(accessibility)
        txtE_low_10->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txtE_low_10->setUndoRedoEnabled(false);
        txtE_low_10->setOverwriteMode(true);
        txtE_low_10->setTabStopWidth(2);
        txtE_low_10->setAcceptRichText(true);
        label_24 = new QLabel(groupBox_24);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(20, 50, 101, 20));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_24->setPalette(palette14);
        label_24->setFont(font);
        label_24->setFocusPolicy(Qt::ClickFocus);
        label_24->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_24->setFrameShadow(QFrame::Raised);
        label_24->setLineWidth(2);
        stackedWidget->addWidget(page_5);
        page_8 = new QWidget();
        page_8->setObjectName(QString::fromUtf8("page_8"));
        groupBox_20 = new QGroupBox(page_8);
        groupBox_20->setObjectName(QString::fromUtf8("groupBox_20"));
        groupBox_20->setGeometry(QRect(90, 40, 471, 241));
        CHb_pic12_BODEN1_2 = new QCheckBox(groupBox_20);
        CHb_pic12_BODEN1_2->setObjectName(QString::fromUtf8("CHb_pic12_BODEN1_2"));
        CHb_pic12_BODEN1_2->setGeometry(QRect(120, 130, 70, 17));
        CHb_pic12_wdt_4 = new QCheckBox(groupBox_20);
        CHb_pic12_wdt_4->setObjectName(QString::fromUtf8("CHb_pic12_wdt_4"));
        CHb_pic12_wdt_4->setGeometry(QRect(120, 10, 70, 17));
        CHb_pic12_CP_3 = new QCheckBox(groupBox_20);
        CHb_pic12_CP_3->setObjectName(QString::fromUtf8("CHb_pic12_CP_3"));
        CHb_pic12_CP_3->setGeometry(QRect(120, 70, 70, 17));
        CHb_pic12_BODEN0_2 = new QCheckBox(groupBox_20);
        CHb_pic12_BODEN0_2->setObjectName(QString::fromUtf8("CHb_pic12_BODEN0_2"));
        CHb_pic12_BODEN0_2->setGeometry(QRect(120, 110, 70, 17));
        CHb_pic12_pwrte_3 = new QCheckBox(groupBox_20);
        CHb_pic12_pwrte_3->setObjectName(QString::fromUtf8("CHb_pic12_pwrte_3"));
        CHb_pic12_pwrte_3->setGeometry(QRect(120, 30, 70, 17));
        CHb_pic12_cpd_3 = new QCheckBox(groupBox_20);
        CHb_pic12_cpd_3->setObjectName(QString::fromUtf8("CHb_pic12_cpd_3"));
        CHb_pic12_cpd_3->setGeometry(QRect(120, 90, 70, 17));
        CHb_pic12_boden_3 = new QCheckBox(groupBox_20);
        CHb_pic12_boden_3->setObjectName(QString::fromUtf8("CHb_pic12_boden_3"));
        CHb_pic12_boden_3->setGeometry(QRect(120, 50, 70, 17));
        label_16 = new QLabel(groupBox_20);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(340, 30, 61, 20));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_16->setPalette(palette15);
        label_16->setFont(font);
        label_16->setFocusPolicy(Qt::ClickFocus);
        label_16->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_16->setFrameShadow(QFrame::Raised);
        label_16->setLineWidth(2);
        label_pic12_2010 = new QLabel(groupBox_20);
        label_pic12_2010->setObjectName(QString::fromUtf8("label_pic12_2010"));
        label_pic12_2010->setGeometry(QRect(410, 30, 46, 21));
        label_pic12_2010->setFont(font);
        CHb_pic12_IESO_2 = new QCheckBox(groupBox_20);
        CHb_pic12_IESO_2->setObjectName(QString::fromUtf8("CHb_pic12_IESO_2"));
        CHb_pic12_IESO_2->setGeometry(QRect(120, 150, 70, 17));
        CHb_pic12_FCMEM_2 = new QCheckBox(groupBox_20);
        CHb_pic12_FCMEM_2->setObjectName(QString::fromUtf8("CHb_pic12_FCMEM_2"));
        CHb_pic12_FCMEM_2->setGeometry(QRect(120, 170, 70, 17));
        CHb_pic12_WURE_2 = new QCheckBox(groupBox_20);
        CHb_pic12_WURE_2->setObjectName(QString::fromUtf8("CHb_pic12_WURE_2"));
        CHb_pic12_WURE_2->setGeometry(QRect(120, 190, 70, 17));
        stackedWidget->addWidget(page_8);
        pagePicFuseSettings = new PicFuseSettings();
        pagePicFuseSettings->setObjectName(QString::fromUtf8("pagePicFuseSettings"));
        stackedWidget->addWidget(pagePicFuseSettings);
        pageAvrFuseSettings = new AvrFuseSettings();
        pageAvrFuseSettings->setObjectName(QString::fromUtf8("pageAvrFuseSettings"));
        gridLayout_2 = new QGridLayout(pageAvrFuseSettings);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        stackedWidget->addWidget(pageAvrFuseSettings);
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        groupBox_12 = new QGroupBox(page_6);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(490, 170, 131, 80));
        txtE_low_8_10f = new QTextEdit(groupBox_12);
        txtE_low_8_10f->setObjectName(QString::fromUtf8("txtE_low_8_10f"));
        txtE_low_8_10f->setEnabled(true);
        txtE_low_8_10f->setGeometry(QRect(40, 20, 41, 21));
#if QT_CONFIG(whatsthis)
        txtE_low_8_10f->setWhatsThis(QString::fromUtf8(""));
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        txtE_low_8_10f->setAccessibleName(QString::fromUtf8(""));
#endif // QT_CONFIG(accessibility)
        txtE_low_8_10f->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txtE_low_8_10f->setUndoRedoEnabled(false);
        txtE_low_8_10f->setOverwriteMode(true);
        txtE_low_8_10f->setTabStopWidth(2);
        txtE_low_8_10f->setAcceptRichText(true);
        label_11_10f = new QLabel(groupBox_12);
        label_11_10f->setObjectName(QString::fromUtf8("label_11_10f"));
        label_11_10f->setGeometry(QRect(20, 50, 101, 20));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_11_10f->setPalette(palette16);
        label_11_10f->setFont(font);
        label_11_10f->setFocusPolicy(Qt::ClickFocus);
        label_11_10f->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_11_10f->setFrameShadow(QFrame::Raised);
        label_11_10f->setLineWidth(2);
        groupBox_13 = new QGroupBox(page_6);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(270, 60, 161, 191));
        CHb_pic10_wdt = new QCheckBox(groupBox_13);
        CHb_pic10_wdt->setObjectName(QString::fromUtf8("CHb_pic10_wdt"));
        CHb_pic10_wdt->setGeometry(QRect(60, 60, 70, 17));
        CHb_pic10_boden = new QCheckBox(groupBox_13);
        CHb_pic10_boden->setObjectName(QString::fromUtf8("CHb_pic10_boden"));
        CHb_pic10_boden->setGeometry(QRect(60, 80, 70, 17));
        CHb_pic10_CP = new QCheckBox(groupBox_13);
        CHb_pic10_CP->setObjectName(QString::fromUtf8("CHb_pic10_CP"));
        CHb_pic10_CP->setGeometry(QRect(60, 40, 70, 17));
        label_11 = new QLabel(groupBox_13);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(20, 120, 61, 20));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_11->setPalette(palette17);
        label_11->setFont(font);
        label_11->setFocusPolicy(Qt::ClickFocus);
        label_11->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_11->setFrameShadow(QFrame::Raised);
        label_11->setLineWidth(2);
        label_12 = new QLabel(groupBox_13);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(90, 120, 46, 21));
        label_12->setFont(font);
        groupBox_15 = new QGroupBox(page_6);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(40, 170, 141, 81));
        txtE_low_8_10f_osc = new QTextEdit(groupBox_15);
        txtE_low_8_10f_osc->setObjectName(QString::fromUtf8("txtE_low_8_10f_osc"));
        txtE_low_8_10f_osc->setEnabled(true);
        txtE_low_8_10f_osc->setGeometry(QRect(80, 40, 31, 21));
#if QT_CONFIG(whatsthis)
        txtE_low_8_10f_osc->setWhatsThis(QString::fromUtf8(""));
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        txtE_low_8_10f_osc->setAccessibleName(QString::fromUtf8(""));
#endif // QT_CONFIG(accessibility)
        txtE_low_8_10f_osc->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        txtE_low_8_10f_osc->setUndoRedoEnabled(false);
        txtE_low_8_10f_osc->setOverwriteMode(true);
        txtE_low_8_10f_osc->setTabStopWidth(2);
        txtE_low_8_10f_osc->setAcceptRichText(true);
        label_11_10f_osc = new QLabel(groupBox_15);
        label_11_10f_osc->setObjectName(QString::fromUtf8("label_11_10f_osc"));
        label_11_10f_osc->setGeometry(QRect(20, 40, 51, 20));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_11_10f_osc->setPalette(palette18);
        label_11_10f_osc->setFont(font);
        label_11_10f_osc->setFocusPolicy(Qt::ClickFocus);
        label_11_10f_osc->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_11_10f_osc->setFrameShadow(QFrame::Raised);
        label_11_10f_osc->setLineWidth(2);
        stackedWidget->addWidget(page_6);

        gridLayout->addWidget(stackedWidget, 0, 0, 1, 1);


        retranslateUi(FuseSettings);

        stackedWidget->setCurrentIndex(6);


        QMetaObject::connectSlotsByName(FuseSettings);
    } // setupUi

    void retranslateUi(QWidget *FuseSettings)
    {
        FuseSettings->setWindowTitle(QCoreApplication::translate("FuseSettings", "Form", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("FuseSettings", "ID", nullptr));
        txtE_low_6->setHtml(QCoreApplication::translate("FuseSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FFFF</span></p></body></html>", nullptr));
        label_5->setText(QCoreApplication::translate("FuseSettings", "0x2000..0x2003", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("FuseSettings", "ON/OFF", nullptr));
        CHb_pic12_wdt->setText(QCoreApplication::translate("FuseSettings", "WDTE", nullptr));
        CHb_pic12_pwrte->setText(QCoreApplication::translate("FuseSettings", "PWRTE", nullptr));
        CHb_pic12_boden->setText(QCoreApplication::translate("FuseSettings", "BODEN", nullptr));
        CHb_pic12_wdt_2->setText(QCoreApplication::translate("FuseSettings", "LVP", nullptr));
        CHb_pic12_cpd->setText(QCoreApplication::translate("FuseSettings", "CPD", nullptr));
        CHb_pic12_CP->setText(QCoreApplication::translate("FuseSettings", "CP", nullptr));
        label_6->setText(QCoreApplication::translate("FuseSettings", "0x2007:", nullptr));
        label_7->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("FuseSettings", "-WRT-", nullptr));
        Rd_pi12_03->setText(QCoreApplication::translate("FuseSettings", "HIGHEST   0X03", nullptr));
        Rd_pi16_pof_2->setText(QCoreApplication::translate("FuseSettings", "Mid high    0x02", nullptr));
        Rd_pi16_pof_3->setText(QCoreApplication::translate("FuseSettings", "Mid low     0X01", nullptr));
        Rd_pi16_00->setText(QCoreApplication::translate("FuseSettings", "Lowest      0x00", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("FuseSettings", "-OSC-", nullptr));
        Rd_pi12_lp->setText(QCoreApplication::translate("FuseSettings", "Lp", nullptr));
        Rd_pi12_xt->setText(QCoreApplication::translate("FuseSettings", "XT", nullptr));
        Rd_pi12_hs->setText(QCoreApplication::translate("FuseSettings", "HS", nullptr));
        Rd_pi12_ec_io->setText(QCoreApplication::translate("FuseSettings", "EC/IO", nullptr));
        Rd_pi12_osc_io->setText(QCoreApplication::translate("FuseSettings", "int OS  IO", nullptr));
        Rd_pi12_osc_clkout->setText(QCoreApplication::translate("FuseSettings", "int osc CLKOUT", nullptr));
        Rd_pi12_rc_io->setText(QCoreApplication::translate("FuseSettings", "RC  IO", nullptr));
        Rd_pi12_rc_5->setText(QCoreApplication::translate("FuseSettings", "RC CLKOUT", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("FuseSettings", "ON/OFF", nullptr));
        CHb_pic16_wdt_3->setText(QCoreApplication::translate("FuseSettings", "WDTE", nullptr));
        CHb_pic16_pwrte_2->setText(QCoreApplication::translate("FuseSettings", "PWRTE", nullptr));
        CHb_pic16_boden_2->setText(QCoreApplication::translate("FuseSettings", "BODEN", nullptr));
        CHb_pic16_wdt_4->setText(QCoreApplication::translate("FuseSettings", "LVP", nullptr));
        CHb_pic16_cpd_2->setText(QCoreApplication::translate("FuseSettings", "CPD", nullptr));
        CHb_pic16_CP_2->setText(QCoreApplication::translate("FuseSettings", "CP", nullptr));
        label_8->setText(QCoreApplication::translate("FuseSettings", "0x2007:", nullptr));
        label_9->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("FuseSettings", "-WRT-", nullptr));
        Rd_pi16_pof_5->setText(QCoreApplication::translate("FuseSettings", "OFF", nullptr));
        Rd_pi16_pof_6->setText(QCoreApplication::translate("FuseSettings", "0000h..00FFh", nullptr));
        Rd_pi16_pof_7->setText(QCoreApplication::translate("FuseSettings", "0000h..07FFh", nullptr));
        Rd_pi16_pof_8->setText(QCoreApplication::translate("FuseSettings", "0000h..0FFFh", nullptr));
        groupBox_10->setTitle(QCoreApplication::translate("FuseSettings", "-OSC-", nullptr));
        Rd_pi16_lp_2->setText(QCoreApplication::translate("FuseSettings", "Lp", nullptr));
        Rd_pi16_xt_2->setText(QCoreApplication::translate("FuseSettings", "XT", nullptr));
        Rd_pi16_hs_2->setText(QCoreApplication::translate("FuseSettings", "HS", nullptr));
        Rd_pi16_rc_2->setText(QCoreApplication::translate("FuseSettings", "RC", nullptr));
        CHb_pic16_debug_2->setText(QCoreApplication::translate("FuseSettings", "DEBUG", nullptr));
        groupBox_11->setTitle(QCoreApplication::translate("FuseSettings", "ID", nullptr));
        txtE_low_7->setHtml(QCoreApplication::translate("FuseSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FFFF</span></p></body></html>", nullptr));
        label_10->setText(QCoreApplication::translate("FuseSettings", "0x2000..0x2003", nullptr));
        groupBox_25->setTitle(QCoreApplication::translate("FuseSettings", "ON/OFF", nullptr));
        groupBox_28->setTitle(QCoreApplication::translate("FuseSettings", "-CALIBRATION-", nullptr));
        CHb_pic12_BOR0_5->setText(QCoreApplication::translate("FuseSettings", "BOR0", nullptr));
        CHb_pic12_BOR1_5->setText(QCoreApplication::translate("FuseSettings", "BOR1", nullptr));
        CHb_pic12_BOR2_5->setText(QCoreApplication::translate("FuseSettings", "BOR2", nullptr));
        CHb_pic12_POR2_4->setText(QCoreApplication::translate("FuseSettings", "POR2", nullptr));
        CHb_pic12_POR0_5->setText(QCoreApplication::translate("FuseSettings", "POR0", nullptr));
        CHb_pic12_POR1_5->setText(QCoreApplication::translate("FuseSettings", "POR1", nullptr));
        CHb_pic12_fcalo_5->setText(QCoreApplication::translate("FuseSettings", "FCAL0", nullptr));
        CHb_pic12_fcalo1_5->setText(QCoreApplication::translate("FuseSettings", "FCAL1", nullptr));
        CHb_pic12_fcalo2_5->setText(QCoreApplication::translate("FuseSettings", "FCAL2", nullptr));
        CHb_pic12_fcalo3_5->setText(QCoreApplication::translate("FuseSettings", "FCAL3", nullptr));
        CHb_pic12_fcalo6_5->setText(QCoreApplication::translate("FuseSettings", "FCAL6", nullptr));
        CHb_pic12_fcalo5_5->setText(QCoreApplication::translate("FuseSettings", "FCAL5", nullptr));
        CHb_pic12_fcalo4_5->setText(QCoreApplication::translate("FuseSettings", "FCAL4", nullptr));
        label_29->setText(QCoreApplication::translate("FuseSettings", "0x2008:", nullptr));
        label_pic12_2019->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        CHb_pic12_update_cal_5->setText(QCoreApplication::translate("FuseSettings", "Update Calibration", nullptr));
        groupBox_29->setTitle(QCoreApplication::translate("FuseSettings", "-OSC-", nullptr));
        Rd_pi12_lp_6->setText(QCoreApplication::translate("FuseSettings", "Lp", nullptr));
        Rd_pi12_xt_6->setText(QCoreApplication::translate("FuseSettings", "XT", nullptr));
        Rd_pi12_hs_6->setText(QCoreApplication::translate("FuseSettings", "HS", nullptr));
        Rd_pi12_ec_io_6->setText(QCoreApplication::translate("FuseSettings", "EC/IO", nullptr));
        Rd_pi12_osc_io_6->setText(QCoreApplication::translate("FuseSettings", "int OS  IO", nullptr));
        Rd_pi12_osc_clkout_6->setText(QCoreApplication::translate("FuseSettings", "int osc CLKOUT", nullptr));
        Rd_pi12_rc_io_6->setText(QCoreApplication::translate("FuseSettings", "EXTRCIO", nullptr));
        Rd_pi12_rc_10->setText(QCoreApplication::translate("FuseSettings", "EXTRC", nullptr));
        CHb_pic12_BODEN1_5->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_wdt_7->setText(QCoreApplication::translate("FuseSettings", "WDTE", nullptr));
        CHb_pic12_CP_6->setText(QCoreApplication::translate("FuseSettings", "CP", nullptr));
        CHb_pic12_BODEN0_5->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_pwrte_6->setText(QCoreApplication::translate("FuseSettings", "PWRTE", nullptr));
        CHb_pic12_cpd_6->setText(QCoreApplication::translate("FuseSettings", "CPD", nullptr));
        CHb_pic12_boden_6->setText(QCoreApplication::translate("FuseSettings", "BODEN", nullptr));
        label_31->setText(QCoreApplication::translate("FuseSettings", "0x2007:", nullptr));
        label_pic12_2021->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        CHb_pic12_IESO_5->setText(QCoreApplication::translate("FuseSettings", "IESO", nullptr));
        CHb_pic12_FCMEM_5->setText(QCoreApplication::translate("FuseSettings", "FCMEM", nullptr));
        CHb_pic12_WURE_5->setText(QCoreApplication::translate("FuseSettings", "WURE", nullptr));
        groupBox_30->setTitle(QCoreApplication::translate("FuseSettings", "ID", nullptr));
        txtE_low_12->setHtml(QCoreApplication::translate("FuseSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FFFF</span></p></body></html>", nullptr));
        label_32->setText(QCoreApplication::translate("FuseSettings", "0x2000..0x2003", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("FuseSettings", "ON/OFF", nullptr));
        groupBox_16->setTitle(QCoreApplication::translate("FuseSettings", "-CALIBRATION-", nullptr));
        CHb_pic12_BOR0->setText(QCoreApplication::translate("FuseSettings", "BOR0", nullptr));
        CHb_pic12_BOR1->setText(QCoreApplication::translate("FuseSettings", "BOR1", nullptr));
        CHb_pic12_BOR2->setText(QCoreApplication::translate("FuseSettings", "BOR2", nullptr));
        CHb_pic12_POR2->setText(QCoreApplication::translate("FuseSettings", "POR2", nullptr));
        CHb_pic12_POR0->setText(QCoreApplication::translate("FuseSettings", "POR0", nullptr));
        CHb_pic12_POR1->setText(QCoreApplication::translate("FuseSettings", "POR1", nullptr));
        CHb_pic12_fcalo->setText(QCoreApplication::translate("FuseSettings", "FCAL0", nullptr));
        CHb_pic12_fcalo1->setText(QCoreApplication::translate("FuseSettings", "FCAL1", nullptr));
        CHb_pic12_fcalo2->setText(QCoreApplication::translate("FuseSettings", "FCAL2", nullptr));
        CHb_pic12_fcalo3->setText(QCoreApplication::translate("FuseSettings", "FCAL3", nullptr));
        CHb_pic12_fcalo6->setText(QCoreApplication::translate("FuseSettings", "FCAL6", nullptr));
        CHb_pic12_fcalo5->setText(QCoreApplication::translate("FuseSettings", "FCAL5", nullptr));
        CHb_pic12_fcalo4->setText(QCoreApplication::translate("FuseSettings", "FCAL4", nullptr));
        CHb_pic12_lvd0->setText(QCoreApplication::translate("FuseSettings", "LVD0", nullptr));
        CHb_pic12_lvd1->setText(QCoreApplication::translate("FuseSettings", "LVD1", nullptr));
        CHb_pic12_lvd2->setText(QCoreApplication::translate("FuseSettings", "LVD2", nullptr));
        CHb_pic12_WUR0->setText(QCoreApplication::translate("FuseSettings", "WUR0", nullptr));
        CHb_pic12_WUR2->setText(QCoreApplication::translate("FuseSettings", "WUR1", nullptr));
        CHb_pic12_WUR3->setText(QCoreApplication::translate("FuseSettings", "WUR2", nullptr));
        label_14->setText(QCoreApplication::translate("FuseSettings", "0x2008:", nullptr));
        label_pic12_2008->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        label_18->setText(QCoreApplication::translate("FuseSettings", "0x2009:", nullptr));
        label_pic12_2009->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        CHb_pic12_update_cal->setText(QCoreApplication::translate("FuseSettings", "Update Calibration", nullptr));
        groupBox_17->setTitle(QCoreApplication::translate("FuseSettings", "-OSC-", nullptr));
        Rd_pi12_lp_2->setText(QCoreApplication::translate("FuseSettings", "Lp", nullptr));
        Rd_pi12_xt_2->setText(QCoreApplication::translate("FuseSettings", "XT", nullptr));
        Rd_pi12_hs_2->setText(QCoreApplication::translate("FuseSettings", "HS", nullptr));
        Rd_pi12_ec_io_2->setText(QCoreApplication::translate("FuseSettings", "EC/IO", nullptr));
        Rd_pi12_osc_io_2->setText(QCoreApplication::translate("FuseSettings", "int OS  IO", nullptr));
        Rd_pi12_osc_clkout_2->setText(QCoreApplication::translate("FuseSettings", "int osc CLKOUT", nullptr));
        Rd_pi12_rc_io_2->setText(QCoreApplication::translate("FuseSettings", "EXTRCIO", nullptr));
        Rd_pi12_rc_6->setText(QCoreApplication::translate("FuseSettings", "EXTRC", nullptr));
        CHb_pic12_BODEN1->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_wdt_3->setText(QCoreApplication::translate("FuseSettings", "WDTE", nullptr));
        CHb_pic12_CP_2->setText(QCoreApplication::translate("FuseSettings", "CP", nullptr));
        CHb_pic12_BODEN0->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_pwrte_2->setText(QCoreApplication::translate("FuseSettings", "PWRTE", nullptr));
        CHb_pic12_cpd_2->setText(QCoreApplication::translate("FuseSettings", "CPD", nullptr));
        CHb_pic12_boden_2->setText(QCoreApplication::translate("FuseSettings", "BODEN", nullptr));
        label_13->setText(QCoreApplication::translate("FuseSettings", "0x2007:", nullptr));
        label_pic12_2007->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        CHb_pic12_IESO->setText(QCoreApplication::translate("FuseSettings", "IESO", nullptr));
        CHb_pic12_FCMEM->setText(QCoreApplication::translate("FuseSettings", "FCMEM", nullptr));
        CHb_pic12_WURE->setText(QCoreApplication::translate("FuseSettings", "WURE", nullptr));
        groupBox_18->setTitle(QCoreApplication::translate("FuseSettings", "ID", nullptr));
        txtE_low_8->setHtml(QCoreApplication::translate("FuseSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FFFF</span></p></body></html>", nullptr));
        label_15->setText(QCoreApplication::translate("FuseSettings", "0x2000..0x2003", nullptr));
        groupBox_19->setTitle(QCoreApplication::translate("FuseSettings", "ON/OFF", nullptr));
        groupBox_22->setTitle(QCoreApplication::translate("FuseSettings", "-CALIBRATION-", nullptr));
        CHb_pic12_BOR0_3->setText(QCoreApplication::translate("FuseSettings", "BOR0", nullptr));
        CHb_pic12_BOR1_3->setText(QCoreApplication::translate("FuseSettings", "BOR1", nullptr));
        CHb_pic12_BOR2_3->setText(QCoreApplication::translate("FuseSettings", "BOR2", nullptr));
        CHb_pic12_POR0_3->setText(QCoreApplication::translate("FuseSettings", "POR0", nullptr));
        CHb_pic12_POR1_3->setText(QCoreApplication::translate("FuseSettings", "POR1", nullptr));
        CHb_pic12_fcalo_3->setText(QCoreApplication::translate("FuseSettings", "FCAL0", nullptr));
        CHb_pic12_fcalo1_3->setText(QCoreApplication::translate("FuseSettings", "FCAL1", nullptr));
        CHb_pic12_fcalo2_3->setText(QCoreApplication::translate("FuseSettings", "FCAL2", nullptr));
        CHb_pic12_fcalo3_3->setText(QCoreApplication::translate("FuseSettings", "FCAL3", nullptr));
        CHb_pic12_fcalo6_3->setText(QCoreApplication::translate("FuseSettings", "FCAL6", nullptr));
        CHb_pic12_fcalo5_3->setText(QCoreApplication::translate("FuseSettings", "FCAL5", nullptr));
        CHb_pic12_fcalo4_3->setText(QCoreApplication::translate("FuseSettings", "FCAL4", nullptr));
        CHb_pic12_lvd0_3->setText(QCoreApplication::translate("FuseSettings", "LVD0", nullptr));
        CHb_pic12_lvd1_3->setText(QCoreApplication::translate("FuseSettings", "LVD1", nullptr));
        CHb_pic12_lvd2_3->setText(QCoreApplication::translate("FuseSettings", "LVD2", nullptr));
        label_21->setText(QCoreApplication::translate("FuseSettings", "0x2008:", nullptr));
        label_pic12_2013->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        label_22->setText(QCoreApplication::translate("FuseSettings", "0x2009:", nullptr));
        label_pic12_2014->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        CHb_pic12_update_cal_3->setText(QCoreApplication::translate("FuseSettings", "Update Calibration", nullptr));
        groupBox_23->setTitle(QCoreApplication::translate("FuseSettings", "-OSC-", nullptr));
        Rd_pi12_lp_4->setText(QCoreApplication::translate("FuseSettings", "Lp", nullptr));
        Rd_pi12_xt_4->setText(QCoreApplication::translate("FuseSettings", "XT", nullptr));
        Rd_pi12_hs_4->setText(QCoreApplication::translate("FuseSettings", "HS", nullptr));
        Rd_pi12_ec_io_4->setText(QCoreApplication::translate("FuseSettings", "EC/IO", nullptr));
        Rd_pi12_osc_io_4->setText(QCoreApplication::translate("FuseSettings", "int OS  IO", nullptr));
        Rd_pi12_osc_clkout_4->setText(QCoreApplication::translate("FuseSettings", "int osc CLKOUT", nullptr));
        Rd_pi12_rc_io_4->setText(QCoreApplication::translate("FuseSettings", "EXTRCIO", nullptr));
        Rd_pi12_rc_8->setText(QCoreApplication::translate("FuseSettings", "EXTRC", nullptr));
        CHb_pic12_BODEN1_3->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_wdt_5->setText(QCoreApplication::translate("FuseSettings", "WDTE", nullptr));
        CHb_pic12_CP_4->setText(QCoreApplication::translate("FuseSettings", "CP", nullptr));
        CHb_pic12_BODEN0_3->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_pwrte_4->setText(QCoreApplication::translate("FuseSettings", "PWRTE", nullptr));
        CHb_pic12_cpd_4->setText(QCoreApplication::translate("FuseSettings", "CPD", nullptr));
        CHb_pic12_boden_4->setText(QCoreApplication::translate("FuseSettings", "BODEN", nullptr));
        label_23->setText(QCoreApplication::translate("FuseSettings", "0x2007:", nullptr));
        label_pic12_2015->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        CHb_pic12_IESO_3->setText(QCoreApplication::translate("FuseSettings", "IESO", nullptr));
        CHb_pic12_FCMEM_3->setText(QCoreApplication::translate("FuseSettings", "FCMEM", nullptr));
        CHb_pic12_WURE_3->setText(QCoreApplication::translate("FuseSettings", "WURE", nullptr));
        groupBox_24->setTitle(QCoreApplication::translate("FuseSettings", "ID", nullptr));
        txtE_low_10->setHtml(QCoreApplication::translate("FuseSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FFFF</span></p></body></html>", nullptr));
        label_24->setText(QCoreApplication::translate("FuseSettings", "0x2000..0x2003", nullptr));
        groupBox_20->setTitle(QCoreApplication::translate("FuseSettings", "-ON/OFF-", nullptr));
        CHb_pic12_BODEN1_2->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_wdt_4->setText(QCoreApplication::translate("FuseSettings", "WDTE", nullptr));
        CHb_pic12_CP_3->setText(QCoreApplication::translate("FuseSettings", "CP", nullptr));
        CHb_pic12_BODEN0_2->setText(QCoreApplication::translate("FuseSettings", "BODEN0", nullptr));
        CHb_pic12_pwrte_3->setText(QCoreApplication::translate("FuseSettings", "PWRTE", nullptr));
        CHb_pic12_cpd_3->setText(QCoreApplication::translate("FuseSettings", "CPD", nullptr));
        CHb_pic12_boden_3->setText(QCoreApplication::translate("FuseSettings", "BODEN", nullptr));
        label_16->setText(QCoreApplication::translate("FuseSettings", "0x2007:", nullptr));
        label_pic12_2010->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        CHb_pic12_IESO_2->setText(QCoreApplication::translate("FuseSettings", "IESO", nullptr));
        CHb_pic12_FCMEM_2->setText(QCoreApplication::translate("FuseSettings", "FCMEM", nullptr));
        CHb_pic12_WURE_2->setText(QCoreApplication::translate("FuseSettings", "WURE", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("FuseSettings", "ID", nullptr));
        txtE_low_8_10f->setHtml(QCoreApplication::translate("FuseSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FFFF</span></p></body></html>", nullptr));
        label_11_10f->setText(QCoreApplication::translate("FuseSettings", "0x100..0x103", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("FuseSettings", "ON/OFF", nullptr));
        CHb_pic10_wdt->setText(QCoreApplication::translate("FuseSettings", "WDTE", nullptr));
        CHb_pic10_boden->setText(QCoreApplication::translate("FuseSettings", "MCLRE", nullptr));
        CHb_pic10_CP->setText(QCoreApplication::translate("FuseSettings", "CP", nullptr));
        label_11->setText(QCoreApplication::translate("FuseSettings", "0x2007:", nullptr));
        label_12->setText(QCoreApplication::translate("FuseSettings", "3FFFh", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("FuseSettings", "-Back OSCCAL -", nullptr));
        txtE_low_8_10f_osc->setHtml(QCoreApplication::translate("FuseSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">????</span></p></body></html>", nullptr));
        label_11_10f_osc->setText(QCoreApplication::translate("FuseSettings", "0X104", nullptr));
    } // retranslateUi

};

namespace Ui {
    class FuseSettings: public Ui_FuseSettings {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FUSESETTINGS_H
